from __future__ import annotations

"""
answerer_v2.py

Answerer-v2: phase-driven graph-reasoning controller.

Runs entirely on local GGUF weights via llama.cpp — no network APIs.

Core idea: the session graph IS the chain of thought.

  The controller's job each step is to WRITE a node or edge into the
  session graph. The final answer is composed deterministically from the
  graph (by walking plan_steps and their grounded conclusions in order),
  not free-generated by the LLM. Without the graph, there is no answer.

Phases:
  PLAN    (step 0)        emit PLAN with 2-4 short subgoals
  EXPLORE (steps 1..N-2)  alternate EXPAND_NODE (gather) and NOTE/CONCLUDE
                          (write) until every plan_step has >=1 grounded
                          conclusion
  CLOSE   (last steps)    fill any underexplored plan_step, then
                          FINALIZE_ANSWER

Hard rules enforced by execute_action:
  - NOTE / CONCLUDE require non-empty supports of valid session node ids.
  - The transitive support ancestry of every NOTE / CONCLUDE must include
    at least one evidence node (no free-floating claims).
  - Out-of-phase actions are rejected and the step is wasted (the error is
    fed back to the next prompt).
"""

import datetime
import json
import os
import re
import uuid
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Set, Tuple

import torch

from graph_core import MemoryGraph, lexical_overlap
from answerer_v1 import (
    AnswerPacket,
    MAX_STEPS,
    PATH_DEPTH_LIMIT,
    SessionGraph,
    SessionNode,
    classify_question_type,
    find_paths_bfs,
    find_all_paths_from_question,
    find_contradictions_on_paths,
    rank_paths,
    retrieve_anchors as retrieve_anchors_legacy,
    expand_node,
    init_frontier_from_anchors,
    build_frontier_from_paths,
    run_pred_and_apply,
    _format_path_text,
)
from anchor_retrieval import retrieve_anchors_v2


# ---------------------------------------------------------------------------
# Phases
# ---------------------------------------------------------------------------

class Phase(str, Enum):
    PLAN = "PLAN"
    EXPLORE = "EXPLORE"
    CLOSE = "CLOSE"


# ---------------------------------------------------------------------------
# Action types (9 total — see module docstring)
# ---------------------------------------------------------------------------

class ActionType(str, Enum):
    PLAN = "PLAN"
    EXPAND_NODE = "EXPAND_NODE"
    NOTE = "NOTE"
    CONCLUDE = "CONCLUDE"
    VERIFY_EDGE = "VERIFY_EDGE"
    CREATE_HYPOTHESIS = "CREATE_HYPOTHESIS"
    RUN_PRED_LOCAL = "RUN_PRED_LOCAL"
    FINALIZE_ANSWER = "FINALIZE_ANSWER"
    STOP = "STOP"


TOOL_DESCRIPTIONS: Dict[ActionType, str] = {
    ActionType.PLAN: (
        "Write 2-4 short subgoals as plan_step nodes. Step 0 only. "
        'Args: {"steps": ["subgoal 1", "subgoal 2", ...]}.'
    ),
    ActionType.EXPAND_NODE: (
        "Pull a frontier node's neighbors from the main graph into the "
        "session as evidence. Use when the focus plan_step lacks evidence. "
        'Args: {"node_id": "<frontier id>"}.'
    ),
    ActionType.NOTE: (
        "Write a working fact extracted from gathered evidence. "
        "REQUIRED: every support id must already exist in the session AND "
        "at least one transitive ancestor must be evidence. "
        "support_usage is REQUIRED: declare what you extracted from each "
        "cited support. "
        'Args: {"text": "...", "supports": ["ev_id", "n_1", ...], '
        '"support_usage": {"ev_id": "what was used from that node", ...}, '
        '"plan_step": "ps_1" (optional)}.'
    ),
    ActionType.CONCLUDE: (
        "Write a partial answer for one plan_step. Same grounding rules as "
        "NOTE; plan_step is REQUIRED. support_usage is REQUIRED. "
        'Args: {"text": "...", "supports": ["ev_id", "n_1", ...], '
        '"support_usage": {"ev_id": "what was used from that node", ...}, '
        '"plan_step": "ps_1"}.'
    ),
    ActionType.VERIFY_EDGE: (
        "Confirm a draft edge after evidence is in. "
        'Args: {"src": "...", "dst": "..."}.'
    ),
    ActionType.CREATE_HYPOTHESIS: (
        "Add a tentative claim (NOT grounded). Promote to NOTE later if "
        "evidence appears. "
        'Args: {"text": "...", "parent": "<node_id>"}.'
    ),
    ActionType.RUN_PRED_LOCAL: (
        "Ask the PRED model to propose new edges/bridges between focus "
        "nodes. Only useful in EXPLORE. "
        'Args: {"focus_nodes": ["id1", "id2"]}.'
    ),
    ActionType.FINALIZE_ANSWER: (
        "Mark the graph as ready for deterministic readout. Allowed in "
        "EXPLORE only when every plan_step has at least one grounded "
        "conclusion; always allowed in CLOSE. No args."
    ),
    ActionType.STOP: (
        "End the loop. Use only after FINALIZE_ANSWER or when the task is "
        "genuinely impossible. No args."
    ),
}


PHASE_VALID_ACTIONS: Dict[Phase, Set[ActionType]] = {
    Phase.PLAN: {ActionType.PLAN},
    Phase.EXPLORE: {
        ActionType.EXPAND_NODE, ActionType.NOTE, ActionType.CONCLUDE,
        ActionType.VERIFY_EDGE, ActionType.CREATE_HYPOTHESIS,
        ActionType.RUN_PRED_LOCAL, ActionType.FINALIZE_ANSWER,
    },
    Phase.CLOSE: {ActionType.CONCLUDE, ActionType.FINALIZE_ANSWER, ActionType.STOP},
}


# Node types written by the controller into the session graph
NODE_PLAN_STEP = "plan_step"
NODE_EVIDENCE = "evidence"     # set by import_memory_nodes / expand_node
NODE_NOTE = "note"
NODE_CONCLUSION = "conclusion"
NODE_HYPOTHESIS = "hypothesis"
NODE_QUESTION = "question"

# Edge relations written by the controller. canonical_relation() will
# normalize "supports" -> "support" and leave the others as-is.
REL_SUPPORTS = "supports"        # stored as "support"
REL_PART_OF = "part_of"
REL_DERIVED_FROM = "derived_from"
REL_FOCUS_OF = "focus_of"
REL_CONTRADICTS = "contradicts"  # stored as "contradict"


@dataclass
class Action:
    action_type: ActionType
    args: Dict[str, Any] = field(default_factory=dict)
    thought_summary: str = ""
    reason: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "action": self.action_type.value,
            "args": dict(self.args),
            "thought_summary": self.thought_summary,
            "reason": self.reason,
        }

    @staticmethod
    def from_dict(d: Dict[str, Any]) -> Action:
        atype_str = str(d.get("action", "STOP"))
        try:
            atype = ActionType(atype_str)
        except ValueError:
            atype = ActionType.STOP
        return Action(
            action_type=atype,
            args=dict(d.get("args", {})),
            thought_summary=str(d.get("thought_summary", "")),
            reason=str(d.get("reason", "")),
        )


@dataclass
class ActionResult:
    action: Action
    success: bool
    summary: str = ""
    new_paths: int = 0
    new_nodes: int = 0
    new_edges: int = 0
    error: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "action": self.action.action_type.value,
            "success": self.success,
            "summary": self.summary,
            "new_paths": self.new_paths,
            "new_nodes": self.new_nodes,
            "new_edges": self.new_edges,
            "error": self.error,
        }


# ---------------------------------------------------------------------------
# Phase / coverage / grounding helpers
# ---------------------------------------------------------------------------

def compute_phase(step: int, max_steps: int) -> Phase:
    if step == 0:
        return Phase.PLAN
    if step >= max_steps - 1:
        return Phase.CLOSE
    return Phase.EXPLORE


def adaptive_max_steps(plan_size: int, *, hard_cap: int = 48, floor: int = 8) -> int:
    """Estimate per-question step budget from the model's plan size.

    Each plan_step typically needs:
      - 1 EXPLORE turn to gather/expand evidence
      - 1 EXPLORE turn to NOTE or CONCLUDE
    Plus 1 turn for PLAN and 1 for FINALIZE_ANSWER. Add slack of two extra
    turns per plan_step for retries / VERIFY_EDGE / etc. The extra +2 over
    earlier (was `max(2, plan_size)`) ensures the model has room for an
    explicit FINALIZE_ANSWER even at boundary plan sizes (plan_size=4
    previously got budget=14 with zero finalize headroom).

    Capped at `hard_cap` to prevent runaway on pathological plans; floored
    at `floor` so very tiny plans still get sensible headroom.

      plan_size  ->  budget
              2  ->  8
              3  ->  13
              4  ->  16
              5  ->  19
             10  ->  34
             20  ->  48 (capped)
    """
    needed = 2 * plan_size + 2
    slack = max(2, plan_size + 2)
    return min(hard_cap, max(floor, needed + slack))


def get_plan_steps(session: SessionGraph) -> List[SessionNode]:
    plan = [n for n in session.nodes.values() if n.node_type == NODE_PLAN_STEP]
    plan.sort(key=lambda n: n.metadata.get("order", 0))
    return plan


def _next_seq_id(session: SessionGraph, prefix: str) -> str:
    """Return the next sequential id for a given prefix (ps_3, n_2, c_1...)."""
    n = sum(1 for k in session.nodes if k.startswith(f"{prefix}_"))
    return f"{prefix}_{n + 1}"


def _outgoing(session: SessionGraph, src: str, relation: str) -> List[str]:
    canon = _canon(relation)
    return [e.dst for e in session.edges if e.src == src and e.relation == canon]


def _incoming(session: SessionGraph, dst: str, relation: str) -> List[str]:
    canon = _canon(relation)
    return [e.src for e in session.edges if e.dst == dst and e.relation == canon]


def _canon(relation: str) -> str:
    # Mirror canonical_relation alias collapsing for the relations we write
    return {
        "supports": "support",
        "contradicts": "contradict",
    }.get(relation, relation)


def nodes_for_plan_step(
    session: SessionGraph, plan_step_id: str, node_type: str,
) -> List[SessionNode]:
    """Return nodes of given type that are part_of plan_step_id."""
    srcs = _incoming(session, plan_step_id, REL_PART_OF)
    return [session.nodes[s] for s in srcs if s in session.nodes and session.nodes[s].node_type == node_type]


def has_evidence_grounding(
    session: SessionGraph, node_id: str, _visited: Optional[Set[str]] = None,
) -> bool:
    """True iff some transitive 'supports' / 'derived_from' ancestor is evidence."""
    if _visited is None:
        _visited = set()
    if node_id in _visited:
        return False
    _visited.add(node_id)
    node = session.nodes.get(node_id)
    if node is None:
        return False
    if node.node_type == NODE_EVIDENCE:
        return True
    parents = _incoming(session, node_id, REL_SUPPORTS) + _incoming(session, node_id, REL_DERIVED_FROM)
    for p in parents:
        if has_evidence_grounding(session, p, _visited):
            return True
    return False


def plan_step_coverage(session: SessionGraph) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    for ps in get_plan_steps(session):
        notes = nodes_for_plan_step(session, ps.id, NODE_NOTE)
        concls = nodes_for_plan_step(session, ps.id, NODE_CONCLUSION)
        grounded = [c for c in concls if has_evidence_grounding(session, c.id)]
        rows.append({
            "id": ps.id,
            "order": ps.metadata.get("order", 0),
            "text": ps.text,
            "notes": len(notes),
            "conclusions": len(concls),
            "grounded_conclusions": len(grounded),
            "done": len(grounded) >= 1,
        })
    return rows


def coverage_complete(session: SessionGraph) -> bool:
    cov = plan_step_coverage(session)
    return bool(cov) and all(row["done"] for row in cov)


def focus_plan_step(session: SessionGraph) -> Optional[Dict[str, Any]]:
    for row in plan_step_coverage(session):
        if not row["done"]:
            return row
    return None


def valid_actions_for_phase(
    phase: Phase,
    session: SessionGraph,
    *,
    step: int = 0,
    max_steps: int = MAX_STEPS,
    last_action_type: Optional[ActionType] = None,
    pred_available: bool = False,
) -> Set[ActionType]:
    """Phase set with three dynamic constraints layered on:

    1. FINALIZE_ANSWER is hidden in EXPLORE until every plan_step has a
       grounded conclusion.
    2. **Alternation**: if the previous action was EXPAND_NODE, drop
       EXPAND_NODE from this turn so the model is forced to write
       (NOTE / CONCLUDE / VERIFY_EDGE / CREATE_HYPOTHESIS).
    3. **Budget pressure**: when remaining steps fall to <= uncovered
       plan_steps + 1, drop EXPAND_NODE and PRED so every remaining step
       must write toward a conclusion.
    4. RUN_PRED_LOCAL is hidden when no pred_model was supplied.
    """
    valid = set(PHASE_VALID_ACTIONS[phase])

    # Coverage-complete short-circuit: if every plan_step has a grounded
    # conclusion, the only useful actions are finalizing the answer or
    # stopping. This prevents the model from piling more conclusions onto
    # plan_steps that are already DONE.
    if phase == Phase.EXPLORE and coverage_complete(session):
        return {ActionType.FINALIZE_ANSWER, ActionType.STOP}

    if phase == Phase.EXPLORE and not coverage_complete(session):
        valid.discard(ActionType.FINALIZE_ANSWER)

    if phase == Phase.EXPLORE and last_action_type == ActionType.EXPAND_NODE:
        valid.discard(ActionType.EXPAND_NODE)

    if phase == Phase.EXPLORE:
        cov = plan_step_coverage(session)
        uncovered = sum(1 for r in cov if not r["done"])
        # Reserve 1 step for FINALIZE_ANSWER + 1 per uncovered plan_step
        # for at least one CONCLUDE each. When the budget gets tight, no
        # more gathering — pure writing.
        remaining = max_steps - step
        if uncovered > 0 and remaining <= uncovered + 1:
            valid.discard(ActionType.EXPAND_NODE)
            valid.discard(ActionType.RUN_PRED_LOCAL)
            valid.discard(ActionType.CREATE_HYPOTHESIS)

        # If the focus plan_step already has at least one NOTE but zero
        # grounded conclusions, force the model to CONCLUDE instead of
        # piling more NOTEs onto the same step.
        focus = focus_plan_step(session)
        if focus is not None and focus["notes"] >= 1 and focus["grounded_conclusions"] == 0:
            valid.discard(ActionType.NOTE)
            valid.discard(ActionType.EXPAND_NODE)
            valid.discard(ActionType.CREATE_HYPOTHESIS)
            valid.discard(ActionType.RUN_PRED_LOCAL)

    if not pred_available:
        valid.discard(ActionType.RUN_PRED_LOCAL)

    return valid


# ---------------------------------------------------------------------------
# Briefing / state summary for the model
# ---------------------------------------------------------------------------

def _truncate(s: str, n: int) -> str:
    s = s or ""
    return s if len(s) <= n else s[:n - 1] + "…"


def serialize_session_state(
    question: str,
    session: SessionGraph,
    max_paths: int = 5,
    max_nodes: int = 15,
    max_edges: int = 10,
) -> str:
    """Compact state dump (kept for backward compat with existing tests)."""
    lines: List[str] = [
        f"Question: {_truncate(question, 200)}",
        f"Step: {session.step}",
        "",
    ]
    evid = [n for n in session.nodes.values() if n.node_type == NODE_EVIDENCE]
    notes = [n for n in session.nodes.values() if n.node_type == NODE_NOTE]
    concls = [n for n in session.nodes.values() if n.node_type == NODE_CONCLUSION]
    plan_steps = get_plan_steps(session)
    lines.append(f"Evidence: {len(evid)}  Notes: {len(notes)}  Conclusions: {len(concls)}  Plan steps: {len(plan_steps)}")

    active = sorted(
        [p for p in session.paths.values() if p.status == "active"],
        key=lambda p: -p.score,
    )
    lines.append(f"Active paths: {len(active)}")
    if active:
        lines.append("Best paths:")
        for p in active[:max_paths]:
            lines.append(f"  [{p.path_id}] ({p.path_type}, conf={p.confidence:.2f}): {_truncate(_format_path_text(p, session), 150)}")

    contradictions = find_contradictions_on_paths(session, active)
    if contradictions:
        lines.append(f"Contradictions on paths: {len(contradictions)}")
        for pair in contradictions[:3]:
            lines.append(f"  {pair[0]} <-> {pair[1]}")

    frontier_sorted = sorted(session.frontier, key=lambda x: -x.priority)
    if frontier_sorted:
        lines.append(f"Frontier ({len(frontier_sorted)}):")
        for f in frontier_sorted[:5]:
            nid = f.node_id or f.path_id or ""
            lines.append(f"  type={f.item_type} id={nid} reason=\"{f.reason}\" prio={f.priority:.2f}")

    if session.nodes:
        lines.append("Session nodes:")
        for nid in list(session.nodes.keys())[:max_nodes]:
            n = session.nodes[nid]
            lines.append(f"  {nid} [{n.node_type}] {_truncate(n.text, 60)}")
    if session.edges:
        lines.append("Edges:")
        for e in session.edges[:max_edges]:
            lines.append(f"  {e.src} --[{e.relation}]--> {e.dst} ({e.status})")
    return "\n".join(lines)


def build_briefing(
    question: str,
    session: SessionGraph,
    phase: Phase,
    step: int,
    max_steps: int,
    valid_actions: Set[ActionType],
    last_error: Optional[Dict[str, str]] = None,
    *,
    max_visible_nodes: int = 18,
    role_aware: bool = False,
) -> str:
    """Phase-aware state briefing handed to the model."""
    lines: List[str] = []
    lines.append(f"Phase: {phase.value}   step {step}/{max_steps}")
    lines.append(f"Question: {_truncate(question, 240)}")
    lines.append("")

    # Plan + coverage table
    cov = plan_step_coverage(session)
    if not cov:
        if phase == Phase.PLAN:
            lines.append("Plan: <empty — your job this step is to write it via PLAN>")
        else:
            lines.append("Plan: <missing — this should not happen; emit STOP>")
    else:
        lines.append("Plan:")
        focus = focus_plan_step(session)
        for row in cov:
            status = "DONE" if row["done"] else ("FOCUS" if focus and row["id"] == focus["id"] else "PENDING")
            lines.append(
                f"  [{row['id']}] \"{_truncate(row['text'], 80)}\"  "
                f"notes={row['notes']} conclusions={row['conclusions']} grounded={row['grounded_conclusions']}  {status}"
            )
    lines.append("")

    # Focus details
    focus = focus_plan_step(session)
    if focus is not None:
        ps_id = focus["id"]
        notes_here = nodes_for_plan_step(session, ps_id, NODE_NOTE)
        evidence_here = nodes_for_plan_step(session, ps_id, NODE_EVIDENCE)
        lines.append(f"Focus plan_step: {ps_id} \"{_truncate(focus['text'], 100)}\"")
        lines.append(f"  notes={focus['notes']}  conclusions={focus['conclusions']}  grounded={focus['grounded_conclusions']}")
        if notes_here or evidence_here:
            lines.append("  nodes already attached to this focus:")
            for n in (notes_here + evidence_here)[:6]:
                lines.append(f"    {n.id} [{n.node_type}] {_truncate(n.text, 80)}")
                # Show prior support_usage so the model can see HOW it
                # cited each support and stay consistent.
                usage = (n.metadata or {}).get("support_usage") if isinstance(n.metadata, dict) else None
                if usage:
                    for sup_id, used_txt in usage.items():
                        lines.append(f"        used from {sup_id}: {_truncate(used_txt, 80)}")
        lines.append("")

    # Signals
    active = [p for p in session.paths.values() if p.status == "active"]
    contradictions = find_contradictions_on_paths(session, active)
    # Direct contradict edges currently in the session (independent of path search)
    contradict_pairs = [
        (e.src, e.dst) for e in session.edges if e.relation == "contradict"
    ]
    if contradict_pairs:
        lines.append("CONTRADICT EDGES present in session. Cite ONLY the higher-confidence side, NEVER both. The lower-confidence node is typically the misconception:")
        for s, d in contradict_pairs[:5]:
            cs = float(getattr(session.nodes.get(s), "confidence", 0.5)) if s in session.nodes else 0.5
            cd = float(getattr(session.nodes.get(d), "confidence", 0.5)) if d in session.nodes else 0.5
            trust = s if cs >= cd else d
            lines.append(f"  {s} (conf={cs:.2f})  <-[contradict]->  {d} (conf={cd:.2f})   -> trust: {trust}")
        lines.append("")

    signals: List[str] = []
    if active:
        signals.append(f"active paths: {len(active)}")
    if contradictions:
        sample = ", ".join(f"{a}<->{b}" for a, b in contradictions[:2])
        signals.append(f"contradictions: {len(contradictions)} ({sample})")
    high_prio_frontier = sorted(session.frontier, key=lambda x: -x.priority)[:3]
    if high_prio_frontier:
        ftxt = ", ".join(
            f"{f.item_type}:{(f.node_id or f.path_id)}@{f.priority:.2f}"
            for f in high_prio_frontier
        )
        signals.append(f"top frontier: {ftxt}")
    if signals:
        lines.append("Signals: " + "  |  ".join(signals))
        lines.append("")

    # Candidate supports — only evidence/note/conclusion nodes are valid
    # supports, ranked by evidence_score (relevance, hub penalty,
    # contradiction penalty, misconception penalty). The plan_step ids are
    # listed separately so the model can use them as the `plan_step` arg
    # but NOT as supports.
    candidates = [
        n for n in session.nodes.values()
        if n.id != "Q0" and n.node_type in VALID_SUPPORT_TYPES
    ]

    # Stage 3 overlay: when enabled, add a focus/role/contradict-pair
    # bonus on top of the question-only base score so candidate ranking
    # adapts to whichever plan_step is currently in focus. The base
    # evidence_score is unchanged — overlay is purely additive and
    # returns 0.0 when focus is empty.
    if role_aware:
        from anchor_retrieval import stage3_overlay_score
        from roles import detect_plan_step_roles
        focus_now = focus_plan_step(session)
        focus_text = focus_now["text"] if focus_now else ""
        focus_roles = detect_plan_step_roles(focus_text) if focus_text else None
    else:
        focus_text = ""
        focus_roles = None

    def _ranked_score(n: SessionNode) -> float:
        base = evidence_score(session, n.id, question)
        if role_aware and focus_text:
            base += stage3_overlay_score(
                session, n.id,
                focus_text=focus_text,
                focus_roles=focus_roles,
            )
        return base

    candidates.sort(key=lambda n: -_ranked_score(n))

    # Surface misconception nodes as a separate WARNING block above the
    # candidate list so the model cannot miss the labeling.
    misconception_in_session = [n for n in candidates if is_misconception_node(n.id)]
    if misconception_in_session:
        lines.append(
            "WARNING: misconception nodes are present in the session. "
            "Their TEXT BODIES state the WRONG view (suffix `_false` = misconception). "
            "Do NOT cite their text as evidence for the truth. Cite them only to "
            "REFUTE the misconception, and pair with the correct counterpart."
        )
        for n in misconception_in_session[:6]:
            lines.append(f"  [MISCONCEPTION] {n.id}  -- WRONG claim: {_truncate(n.text, 90)}")
        lines.append("")

    if candidates:
        lines.append("Candidate supports (ranked by relevance; cite 1-4 of these):")
        for n in candidates[:max_visible_nodes]:
            s = evidence_score(session, n.id, question)
            tag = " [MISCONCEPTION]" if is_misconception_node(n.id) else ""
            lines.append(f"  {n.id} [{n.node_type}]{tag} score={s:+.2f}  {_truncate(n.text, 80)}")
        lines.append("")

    # Plan-step ids (NOT supports; only valid for the `plan_step` arg)
    plan_ids = [n.id for n in get_plan_steps(session)]
    if plan_ids:
        lines.append(f"Plan-step ids (for the `plan_step` arg, NOT for supports): {plan_ids}")
        lines.append("")

    # Frontier for EXPAND_NODE (only show when EXPAND_NODE is actually allowed)
    if phase == Phase.EXPLORE and ActionType.EXPAND_NODE in valid_actions:
        unexpanded_frontier = [
            f.node_id for f in session.frontier
            if f.item_type == "expand_node" and f.node_id and f.node_id in session.nodes
        ]
        if unexpanded_frontier:
            lines.append(f"Unexpanded frontier (for EXPAND_NODE only): {unexpanded_frontier[:12]}")
            lines.append("")

    # Writing pressure: tell the model explicitly when gathering is blocked
    if phase == Phase.EXPLORE and ActionType.EXPAND_NODE not in valid_actions:
        cov = plan_step_coverage(session)
        uncovered = [r for r in cov if not r["done"]]
        remaining = max_steps - step
        if uncovered:
            ps_ids = ", ".join(r["id"] for r in uncovered)
            lines.append(
                f"WRITE NOW: EXPAND_NODE is disabled this turn "
                f"(remaining={remaining}, uncovered plan_steps={len(uncovered)}: {ps_ids}). "
                f"Pick NOTE or CONCLUDE citing already-gathered evidence."
            )
            lines.append("")

    # Error feedback from previous step
    if last_error:
        lines.append(f"Previous action error: action={last_error.get('action')} reason={last_error.get('reason')}")
        lines.append("Fix the issue: provide valid supports / valid phase / non-empty args.")
        lines.append("")

    # Available actions
    valid_names = sorted(a.value for a in valid_actions)
    lines.append(f"Available actions this phase: {valid_names}")
    lines.append('Output JSON: {"thought_summary": "...", "action": "ACTION", "args": {...}, "reason": "..."}')
    return "\n".join(lines)


def build_pred_context(
    question: str,
    session: SessionGraph,
    focus_node_ids: Optional[List[str]] = None,
    mode: str = "explore",
) -> Dict[str, Any]:
    if not focus_node_ids:
        focus_node_ids = [nid for nid in list(session.nodes.keys())[:5]]
    focus_texts = {nid: session.nodes[nid].text[:100] for nid in focus_node_ids if nid in session.nodes}
    active = [p for p in session.paths.values() if p.status == "active"]
    return {
        "question": question[:300],
        "mode": mode,
        "focus_nodes": focus_node_ids,
        "focus_node_texts": focus_texts,
        "active_paths": [
            {"path_id": p.path_id, "type": p.path_type, "nodes": p.node_ids, "confidence": p.confidence}
            for p in active[:3]
        ],
        "uncertain_edges": [
            [e.src, e.dst, e.relation] for e in session.edges
            if e.status == "draft" and e.confidence < 0.6
        ],
        "step": session.step,
        "total_nodes": len(session.nodes),
        "total_edges": len(session.edges),
    }


# ---------------------------------------------------------------------------
# Action execution
# ---------------------------------------------------------------------------

def _ok(action: Action, summary: str, **kw: Any) -> ActionResult:
    return ActionResult(action, True, summary=summary, **kw)


def _fail(action: Action, summary: str, error: str) -> ActionResult:
    return ActionResult(action, False, summary=summary, error=error)


SUPPORTS_MIN = 1
SUPPORTS_MAX = 4

# Node types that can be cited as a direct support. Plan steps organize
# reasoning but are not evidence; the question itself is not evidence;
# unverified hypotheses are not evidence-grade either.
VALID_SUPPORT_TYPES = {NODE_EVIDENCE, NODE_NOTE, NODE_CONCLUSION}


def _validate_supports(
    session: SessionGraph, supports: Iterable[str],
) -> Tuple[List[str], Optional[str]]:
    """Return (clean_ids, error_message_or_None).

    Rules enforced:
      - 1 to 4 ids
      - every id exists in the session
      - no Q0 (the question)
      - no plan_step / question / unverified hypothesis ids
      - no two supports may be linked by a contradict edge in either
        direction (the model must VERIFY_EDGE first)
    """
    ids = [str(s).strip() for s in supports if str(s).strip()]
    if len(ids) < SUPPORTS_MIN:
        return [], f"supports must contain at least {SUPPORTS_MIN} id"
    if len(ids) > SUPPORTS_MAX:
        # Suggest the top-SUPPORTS_MAX by score so the model can trim in
        # one retry instead of re-picking from scratch.
        q_text = session.nodes["Q0"].text if "Q0" in session.nodes else ""
        scorable = [s for s in ids if s in session.nodes]
        ranked = sorted(scorable, key=lambda s: -evidence_score(session, s, q_text))
        keep = ranked[:SUPPORTS_MAX]
        drop = [s for s in ids if s not in set(keep)]
        return ids, (
            f"too many supports ({len(ids)}); cap is {SUPPORTS_MAX}. "
            f"Keep top-{SUPPORTS_MAX} by relevance: {keep}. Drop: {drop}. "
            f"Reuse your previous text and support_usage entries for the kept ids."
        )

    missing = [s for s in ids if s not in session.nodes]
    if missing:
        return ids, f"unknown support ids: {missing}"

    if any(s == "Q0" for s in ids):
        return ids, "Q0 (the question) is not a valid support"

    invalid_types = [
        s for s in ids if session.nodes[s].node_type not in VALID_SUPPORT_TYPES
    ]
    if invalid_types:
        type_map = {s: session.nodes[s].node_type for s in invalid_types}
        return ids, (
            f"these ids cannot be direct supports: {type_map}. "
            "Only evidence / note / conclusion nodes count as supports — "
            "plan_step ids and hypotheses do not."
        )

    # Reject if any pair of supports is on opposite sides of a contradict
    # edge in the current session graph. The model must pick ONE side
    # (typically the higher-confidence node — see node.confidence) and
    # drop the other from the supports list. VERIFY_EDGE alone does NOT
    # resolve this — it only marks edge.status="verified" without
    # disqualifying either side, so retrying the same pair after a
    # verify still fails.
    for i, a in enumerate(ids):
        for b in ids[i + 1:]:
            if (
                session.edge_between(a, b) and session.edge_between(a, b).relation == "contradict"
            ) or (
                session.edge_between(b, a) and session.edge_between(b, a).relation == "contradict"
            ):
                # Suggest the higher-confidence side concretely.
                conf_a = float(getattr(session.nodes[a], "confidence", 0.5))
                conf_b = float(getattr(session.nodes[b], "confidence", 0.5))
                trusted = a if conf_a >= conf_b else b
                rejected = b if trusted == a else a
                return ids, (
                    f"{a} and {b} are linked by a contradict edge. Pick ONE side "
                    f"and drop the other. {trusted} (confidence {max(conf_a, conf_b):.2f}) "
                    f"is the higher-confidence side; {rejected} "
                    f"(confidence {min(conf_a, conf_b):.2f}) is likely the misconception. "
                    "Do not cite both."
                )

    return ids, None


def is_misconception_node(node_id: str) -> bool:
    """Convention: nodes whose id ends in `_false` carry text bodies that
    state the WRONG view. They are intended to be CITED-AS-MISCONCEPTIONS,
    not as evidence of truth. Naming convention is set by the graph
    builders (see physics1.json, cs4.json).
    """
    nid = (node_id or "").lower()
    return nid.endswith("_false") or nid.endswith("_hyp")


def evidence_score(
    session: SessionGraph, node_id: str, question: str,
) -> float:
    """Cheap relevance score for ranking candidate supports in the briefing.

    Combines lexical relevance to the question with a few structural
    penalties so the model gravitates to specific, on-topic evidence
    instead of hubs, contradicted, or misconception nodes.
    """
    node = session.nodes.get(node_id)
    if node is None:
        return 0.0
    score = float(lexical_overlap(node.text or "", question or ""))
    # Hub penalty: name suggests a high-level cluster node.
    nid = node.id.lower()
    if nid.endswith("_hub") or "_hub_" in nid or nid.endswith("hub"):
        score -= 0.30
    # Degree penalty: anything wired up to too many edges is a hub.
    degree = len(session.all_neighbors(node.id))
    if degree >= 6:
        score -= 0.15
    # Contradiction penalty: node is on either side of a contradict edge.
    for e in session.edges:
        if e.relation == "contradict" and node.id in (e.src, e.dst):
            score -= 0.40
            break
    # Misconception penalty: `_false` body text states the wrong view; the
    # model must NOT cite it as direct evidence for the truth. Demote so
    # the correct counterpart wins ranking. Contradiction-style prompts
    # can still pick it up — the demotion is moderate, not crushing.
    if is_misconception_node(node.id):
        score -= 0.20
    # Type-of-node nudges
    if node.node_type == NODE_CONCLUSION:
        score += 0.05
    elif node.node_type == NODE_NOTE:
        score += 0.02
    return round(score, 3)


def _ensure_evidence_grounding(
    session: SessionGraph, supports: List[str],
) -> Optional[str]:
    """Return error message if no transitive support is evidence."""
    for s in supports:
        node = session.nodes.get(s)
        if node is None:
            continue
        if node.node_type == NODE_EVIDENCE:
            return None
        if has_evidence_grounding(session, s):
            return None
    return (
        "ungrounded: at least one support (transitively) must be an evidence "
        "node. Use EXPAND_NODE first or include an evidence id in supports."
    )


def _do_plan(action: Action, session: SessionGraph) -> ActionResult:
    if get_plan_steps(session):
        return _fail(action, "plan already exists", "plan_already_set")
    raw_steps = action.args.get("steps")
    if not isinstance(raw_steps, list) or not raw_steps:
        return _fail(action, "steps must be a non-empty list", "bad_args")
    steps = [str(s).strip() for s in raw_steps if str(s).strip()]
    if not (2 <= len(steps) <= 6):
        return _fail(action, f"plan must have 2-6 steps (got {len(steps)})", "bad_plan_size")
    added = 0
    for i, text in enumerate(steps):
        pid = f"ps_{i + 1}"
        if pid in session.nodes:
            continue
        session.add_node(SessionNode(
            id=pid, text=text, node_type=NODE_PLAN_STEP,
            confidence=0.7, relevance=0.9,
            metadata={"order": i},
            created_step=session.step,
        ))
        session.add_edge(pid, "Q0", REL_PART_OF, status="verified", confidence=0.9)
        added += 1
    return _ok(action, f"plan written ({added} steps)", new_nodes=added, new_edges=added)


def _import_missing_edges(session: SessionGraph, graph: MemoryGraph) -> int:
    """Pull in any main-graph edges whose endpoints are BOTH now in the
    session but which haven't yet been added. This catches contradict /
    support edges that expand_node misses because they were INCOMING to
    the expanded node rather than outgoing.
    """
    added = 0
    for e in graph.edges:
        src = getattr(e, "src", None) or (e.get("src") if isinstance(e, dict) else None)
        dst = getattr(e, "dst", None) or (e.get("dst") if isinstance(e, dict) else None)
        rel = getattr(e, "relation", None) or (e.get("relation") if isinstance(e, dict) else None) or "related"
        if not src or not dst:
            continue
        if src not in session.nodes or dst not in session.nodes:
            continue
        if session.edge_between(src, dst) is not None:
            continue
        if src == "Q0" or dst == "Q0":
            continue
        session.add_edge(src, dst, rel, status="draft", confidence=0.7)
        added += 1
    return added


def _do_expand_node(action: Action, session: SessionGraph, graph: MemoryGraph) -> ActionResult:
    node_id = str(action.args.get("node_id", "")).strip()
    if not node_id or node_id not in session.nodes:
        return _fail(action, f"node {node_id!r} not in session", "node_not_found")
    if node_id not in graph.nodes:
        return _fail(action, f"node {node_id!r} not in main graph", "not_in_graph")
    n_added = expand_node(session, node_id, graph)
    # expand_node only follows outgoing edges; pick up any edges between
    # already-session-resident nodes that it missed (e.g. contradict edges
    # whose dst is the just-expanded node).
    n_extra_edges = _import_missing_edges(session, graph)
    _drop = lambda items: [
        f for f in items
        if not (f.item_type == "expand_node" and f.node_id == node_id)
    ]
    session.frontier = _drop(session.frontier)
    n_new_paths = 0
    if n_added > 0:
        new_paths = find_paths_bfs(session, "Q0", max_depth=PATH_DEPTH_LIMIT)
        for p in new_paths:
            if p.path_id not in session.paths:
                session.add_path(p)
        build_frontier_from_paths(session, new_paths)
        session.frontier = _drop(session.frontier)
        n_new_paths = len(new_paths)
    return _ok(
        action,
        f"expanded {node_id}: +{n_added} nodes, +{n_new_paths} paths, +{n_extra_edges} edges",
        new_nodes=n_added, new_paths=n_new_paths, new_edges=n_extra_edges,
    )


def _do_note_or_conclude(
    action: Action, session: SessionGraph, *, is_conclusion: bool,
) -> ActionResult:
    text = str(action.args.get("text", "")).strip()
    if not text:
        return _fail(action, "text must be a non-empty string", "empty_text")

    supports = action.args.get("supports", [])
    if not isinstance(supports, list):
        return _fail(action, "supports must be a list", "bad_args")
    clean_supports, err = _validate_supports(session, supports)
    if err:
        return _fail(action, err, "ungrounded" if "Q0" in err or "non-empty" in err else "bad_supports")

    err = _ensure_evidence_grounding(session, clean_supports)
    if err:
        return _fail(action, err, "ungrounded")

    # support_usage map: required for NOTE/CONCLUDE. Forces the model to
    # declare WHAT was extracted from each cited support. Downstream
    # usage_coverage metric will check that each usage string is actually
    # consistent with the support node's text.
    support_usage = action.args.get("support_usage", {})
    if not isinstance(support_usage, dict):
        return _fail(
            action,
            "support_usage must be an object mapping each support id to a "
            "short string describing what was extracted from that support",
            "bad_args",
        )
    clean_usage: Dict[str, str] = {}
    missing_usage = []
    for sid in clean_supports:
        u = support_usage.get(sid)
        if not (isinstance(u, str) and u.strip()):
            missing_usage.append(sid)
        else:
            clean_usage[sid] = u.strip()
    extra_keys = [k for k in support_usage.keys() if k not in set(clean_supports)]
    if missing_usage or extra_keys:
        parts = []
        if missing_usage:
            parts.append(f"missing usage for: {missing_usage}")
        if extra_keys:
            parts.append(f"unknown ids in support_usage: {extra_keys}")
        return _fail(
            action,
            "support_usage keys must exactly equal supports. " + "; ".join(parts),
            "support_usage_mismatch",
        )

    plan_step = str(action.args.get("plan_step", "")).strip()
    if is_conclusion and not plan_step:
        return _fail(action, "CONCLUDE requires plan_step", "missing_plan_step")
    if plan_step and (plan_step not in session.nodes or session.nodes[plan_step].node_type != NODE_PLAN_STEP):
        return _fail(action, f"plan_step {plan_step!r} not found", "bad_plan_step")

    kind = NODE_CONCLUSION if is_conclusion else NODE_NOTE
    prefix = "c" if is_conclusion else "n"
    nid = _next_seq_id(session, prefix)
    session.add_node(SessionNode(
        id=nid, text=text, node_type=kind,
        confidence=0.7 if is_conclusion else 0.6, relevance=0.8,
        metadata={
            "plan_step": plan_step or None,
            "support_usage": clean_usage,
        },
        created_step=session.step,
    ))
    new_edges = 0
    for s in clean_supports:
        session.add_edge(s, nid, REL_SUPPORTS, status="verified", confidence=0.7)
        new_edges += 1
    if plan_step:
        session.add_edge(nid, plan_step, REL_PART_OF, status="verified", confidence=0.9)
        new_edges += 1

    return _ok(
        action,
        f"wrote {kind} {nid} with {len(clean_supports)} supports"
        + (f" under {plan_step}" if plan_step else ""),
        new_nodes=1, new_edges=new_edges,
    )


def _do_verify_edge(action: Action, session: SessionGraph) -> ActionResult:
    src = str(action.args.get("src", "")).strip()
    dst = str(action.args.get("dst", "")).strip()
    if not src or not dst:
        return _fail(action, "src and dst required", "bad_args")
    # Try given direction; if not found, try the reversed direction so the
    # model doesn't have to remember which way the edge was originally
    # stored. Especially important for symmetric relations like contradict
    # (A contradicts B  <=>  B contradicts A) — the model should be able
    # to VERIFY_EDGE either way.
    if session.edge_between(src, dst):
        actual_src, actual_dst = src, dst
    elif session.edge_between(dst, src):
        actual_src, actual_dst = dst, src
    else:
        return _fail(action, f"edge {src}<->{dst} not found in either direction", "edge_not_found")
    session.update_edge_status(actual_src, actual_dst, "verified", confidence=0.85)
    return _ok(action, f"verified {actual_src}->{actual_dst}")


def _do_create_hypothesis(action: Action, session: SessionGraph) -> ActionResult:
    text = str(action.args.get("text", "")).strip()
    parent = str(action.args.get("parent", action.args.get("parent_node", ""))).strip()
    if not text:
        return _fail(action, "text required", "empty_text")
    hid = f"hyp_{uuid.uuid4().hex[:8]}"
    session.add_node(SessionNode(
        id=hid, text=text, node_type=NODE_HYPOTHESIS,
        confidence=0.4, relevance=0.5,
        metadata={"parent": parent or None},
        created_step=session.step,
    ))
    new_edges = 0
    if parent and parent in session.nodes:
        session.add_edge(parent, hid, "related", status="draft", confidence=0.4)
        new_edges = 1
    return _ok(action, f"created hypothesis {hid}", new_nodes=1, new_edges=new_edges)


def _do_run_pred_local(
    action: Action,
    session: SessionGraph,
    graph: MemoryGraph,
    pred_model: Any,
    pred_device: Optional[torch.device],
) -> ActionResult:
    if pred_model is None:
        return _fail(action, "no PRED model available in this run", "no_model")
    if pred_device is None:
        return _fail(action, "no PRED device available", "no_device")
    focus_nodes = action.args.get("focus_nodes", []) or []
    memory_ids = [nid for nid in focus_nodes if nid in graph.nodes]
    if not memory_ids:
        memory_ids = [
            n.source_memory_id for n in session.nodes.values()
            if n.node_type == NODE_EVIDENCE and n.source_memory_id
        ][:5]
    memory_ids = memory_ids[:8]
    n_added = run_pred_and_apply(session, pred_model, session.question, memory_ids, graph, pred_device)
    new_paths = find_paths_bfs(session, "Q0", max_depth=PATH_DEPTH_LIMIT)
    for p in new_paths:
        if p.path_id not in session.paths:
            session.add_path(p)
    build_frontier_from_paths(session, new_paths)
    return _ok(
        action,
        f"PRED proposed +{n_added} nodes, +{len(new_paths)} paths",
        new_nodes=n_added, new_paths=len(new_paths),
    )


def execute_action(
    action: Action,
    session: SessionGraph,
    graph: MemoryGraph,
    pred_model: Any = None,
    pred_device: Optional[torch.device] = None,
) -> ActionResult:
    atype = action.action_type
    if atype == ActionType.PLAN:
        return _do_plan(action, session)
    if atype == ActionType.EXPAND_NODE:
        return _do_expand_node(action, session, graph)
    if atype == ActionType.NOTE:
        return _do_note_or_conclude(action, session, is_conclusion=False)
    if atype == ActionType.CONCLUDE:
        return _do_note_or_conclude(action, session, is_conclusion=True)
    if atype == ActionType.VERIFY_EDGE:
        return _do_verify_edge(action, session)
    if atype == ActionType.CREATE_HYPOTHESIS:
        return _do_create_hypothesis(action, session)
    if atype == ActionType.RUN_PRED_LOCAL:
        return _do_run_pred_local(action, session, graph, pred_model, pred_device)
    # FINALIZE_ANSWER and STOP are handled by the loop, not here.
    return _fail(action, f"action {atype.value} not handled by execute_action", "not_implemented")


# ---------------------------------------------------------------------------
# Deterministic graph -> answer readout
# ---------------------------------------------------------------------------

# Detect code-bearing support nodes so their authoritative text is surfaced
# in the readout instead of being lost behind the model's paraphrase.
_CODE_DETECT_RE = re.compile(
    r"#include\s*[<\"]"
    r"|\bstd::"
    r"|\bint\s+main\s*\("
    r"|\bvector\s*<"
    r"|\btemplate\s*<"
    r"|\blong\s+long\s+\w+\s*\("
    r"|\bnullptr\b"
    r"|\bstruct\s+\w+\s*\{"
    r"|\bdef\s+\w+\s*\("
    r"|->\w"
)


def _node_contains_code(node: SessionNode) -> bool:
    """Detect code-bearing supports for the readout extension.

    Two-tier signal:
      1. Strong: id ends with `_apply` AND text contains both `{` and `;`.
         The `_apply` suffix is a graph-author convention that this node is
         meant to be code; combined with structural code markers (braces +
         semicolons) it generalizes across C/C++/Java/JS regardless of which
         std-lib headers happen to be present.
      2. Fallback: regex over explicit C/C++/Python tokens. Catches
         code-bearing nodes that don't follow the `_apply` suffix.
    """
    txt = node.text or ""
    if not txt:
        return False
    nid = (getattr(node, "id", "") or "").lower()
    if nid.endswith("_apply") and "{" in txt and ";" in txt:
        return True
    return bool(_CODE_DETECT_RE.search(txt))


def compose_graph_readout(session: SessionGraph) -> str:
    plan_steps = get_plan_steps(session)
    if not plan_steps:
        # No plan was ever written; degrade gracefully by listing any
        # grounded conclusions/notes that exist.
        concls = [n for n in session.nodes.values() if n.node_type == NODE_CONCLUSION]
        if not concls:
            notes = [n for n in session.nodes.values() if n.node_type == NODE_NOTE]
            if not notes:
                return "(no plan, no conclusions, no notes — the graph is empty.)"
            return "Notes only (no plan was written):\n" + "\n".join(
                f"  - {_truncate(n.text, 200)}" for n in notes
            )
        return "Conclusions only (no plan was written):\n" + "\n".join(
            f"  - {_truncate(c.text, 200)}" for c in concls
        )

    lines: List[str] = []
    seen_code: Set[str] = set()
    for ps in plan_steps:
        order = ps.metadata.get("order", 0)
        concls = nodes_for_plan_step(session, ps.id, NODE_CONCLUSION)
        grounded = [c for c in concls if has_evidence_grounding(session, c.id)]
        lines.append(f"{order + 1}. {ps.text}")
        if not grounded:
            if concls:
                lines.append("   (ungrounded conclusions only — underexplored)")
            else:
                lines.append("   (underexplored — no conclusions)")
            continue
        seen_text: Set[str] = set()
        for c in grounded:
            key = c.text.strip().lower()
            if key in seen_text:
                continue
            seen_text.add(key)
            supports = _incoming(session, c.id, REL_SUPPORTS)
            sup_str = f"  [supports: {', '.join(supports)}]" if supports else ""
            lines.append(f"   - {c.text}{sup_str}")
            for sup_id in supports:
                if sup_id in seen_code:
                    continue
                sup_node = session.nodes.get(sup_id)
                if sup_node and _node_contains_code(sup_node):
                    seen_code.add(sup_id)
                    lines.append("")
                    lines.append(f"     Source `{sup_id}`:")
                    lines.append("     ```")
                    for src_line in sup_node.text.splitlines():
                        lines.append(f"     {src_line}")
                    lines.append("     ```")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Controller ABC
# ---------------------------------------------------------------------------

class Controller(ABC):
    @abstractmethod
    def choose_action(
        self,
        question: str,
        session: SessionGraph,
        step: int,
        max_steps: int,
        phase: Phase,
        valid_actions: Set[ActionType],
        last_error: Optional[Dict[str, str]] = None,
    ) -> Action:
        ...

    def note_result(self, action: Action, result: ActionResult) -> None:
        """Called after execute_action so the controller can adapt."""
        pass

    @property
    @abstractmethod
    def name(self) -> str:
        ...


# ---------------------------------------------------------------------------
# MockController — deterministic baseline that follows the new protocol
# ---------------------------------------------------------------------------

class MockController(Controller):
    def __init__(self) -> None:
        self._expanded_nodes: Set[str] = set()
        self._verified_edges: Set[Tuple[str, str]] = set()

    @property
    def name(self) -> str:
        return "MockController"

    def choose_action(
        self,
        question: str,
        session: SessionGraph,
        step: int,
        max_steps: int,
        phase: Phase,
        valid_actions: Set[ActionType],
        last_error: Optional[Dict[str, str]] = None,
    ) -> Action:
        if step == 0:
            self._expanded_nodes.clear()
            self._verified_edges.clear()

        if phase == Phase.PLAN:
            steps = self._default_plan(question)
            return Action(ActionType.PLAN, {"steps": steps}, "default 3-step plan")

        if phase == Phase.CLOSE:
            focus = focus_plan_step(session)
            if focus is not None:
                return self._best_conclude_for(session, focus["id"]) or Action(
                    ActionType.FINALIZE_ANSWER, {}, "no more progress possible"
                )
            return Action(ActionType.FINALIZE_ANSWER, {}, "coverage complete")

        # EXPLORE
        if coverage_complete(session):
            return Action(ActionType.FINALIZE_ANSWER, {}, "coverage complete")

        focus = focus_plan_step(session)
        focus_id = focus["id"] if focus else None

        # Conclude when we have at least one note for the focus
        if focus_id is not None:
            notes_here = nodes_for_plan_step(session, focus_id, NODE_NOTE)
            if notes_here:
                supports = [n.id for n in notes_here[:2]]
                text = "; ".join(_truncate(n.text, 80) for n in notes_here[:2])
                return Action(
                    ActionType.CONCLUDE,
                    {
                        "text": f"Based on notes: {text}",
                        "supports": supports,
                        "support_usage": self._stub_usage(session, supports),
                        "plan_step": focus_id,
                    },
                    f"concluding {focus_id} from gathered notes",
                )
            evid_here = nodes_for_plan_step(session, focus_id, NODE_EVIDENCE)
            if not evid_here:
                # Attach an evidence node from existing session evidence to the focus
                any_evid = [n for n in session.nodes.values() if n.node_type == NODE_EVIDENCE]
                if any_evid:
                    e = any_evid[0]
                    return Action(
                        ActionType.NOTE,
                        {
                            "text": _truncate(e.text, 140),
                            "supports": [e.id],
                            "support_usage": self._stub_usage(session, [e.id]),
                            "plan_step": focus_id,
                        },
                        f"first NOTE under {focus_id} citing {e.id}",
                    )

        # Expand an unexpanded frontier item
        frontier_expand = [
            f.node_id for f in sorted(session.frontier, key=lambda x: -x.priority)
            if f.item_type == "expand_node" and f.node_id and f.node_id not in self._expanded_nodes
        ]
        if frontier_expand:
            nid = frontier_expand[0]
            self._expanded_nodes.add(nid)
            return Action(ActionType.EXPAND_NODE, {"node_id": nid}, f"expanding {nid}")

        # If frontier is exhausted but coverage isn't complete, take a NOTE
        # over any evidence we already have
        any_evid = [n for n in session.nodes.values() if n.node_type == NODE_EVIDENCE]
        if any_evid and focus_id is not None:
            e = any_evid[0]
            return Action(
                ActionType.NOTE,
                {
                    "text": _truncate(e.text, 140),
                    "supports": [e.id],
                    "support_usage": self._stub_usage(session, [e.id]),
                    "plan_step": focus_id,
                },
                "fallback NOTE on existing evidence",
            )

        return Action(ActionType.FINALIZE_ANSWER, {}, "no further progress")

    @staticmethod
    def _stub_usage(session: SessionGraph, support_ids: List[str]) -> Dict[str, str]:
        """Mock's lazy usage map — copy each support's text as the usage
        string. Will pass the usage_coverage check trivially because
        cosine(text, text) = 1.0."""
        return {
            sid: _truncate(session.nodes[sid].text or "", 120)
            for sid in support_ids if sid in session.nodes
        }

    def _default_plan(self, question: str) -> List[str]:
        q = question.lower()
        if "compare" in q or " vs " in q or "difference" in q:
            return [
                "Identify each side of the comparison.",
                "Compare them on the key dimension.",
                "State the verdict.",
            ]
        if q.startswith("how ") or "how to" in q or "steps" in q:
            return [
                "List required preconditions.",
                "Describe the procedure step by step.",
                "Note common pitfalls.",
            ]
        return [
            "Identify the key concepts in the question.",
            "Gather supporting evidence from the graph.",
            "State the answer grounded in the evidence.",
        ]

    def _best_conclude_for(self, session: SessionGraph, plan_step_id: str) -> Optional[Action]:
        notes_here = nodes_for_plan_step(session, plan_step_id, NODE_NOTE)
        if notes_here:
            supports = [n.id for n in notes_here[:2]]
            text = "; ".join(_truncate(n.text, 80) for n in notes_here[:2])
            return Action(
                ActionType.CONCLUDE,
                {
                    "text": f"Based on notes: {text}",
                    "supports": supports,
                    "support_usage": self._stub_usage(session, supports),
                    "plan_step": plan_step_id,
                },
                "close-phase conclude",
            )
        any_evid = [n for n in session.nodes.values() if n.node_type == NODE_EVIDENCE]
        if any_evid:
            e = any_evid[0]
            return Action(
                ActionType.CONCLUDE,
                {
                    "text": _truncate(e.text, 140),
                    "supports": [e.id],
                    "support_usage": self._stub_usage(session, [e.id]),
                    "plan_step": plan_step_id,
                },
                "close-phase conclude direct from evidence",
            )
        return None


# ---------------------------------------------------------------------------
# Phase-aware GLM-4.7-Flash via llama-server (HTTP, localhost only)
# ---------------------------------------------------------------------------

GLM_SYSTEM_PROMPT = """You are a graph-reasoning controller. The session graph IS your scratchpad and IS the final answer — there is no separate prose step at the end.

Phases (set by step number, you cannot change them):
  PLAN     (step 0)        emit PLAN with 2-4 short subgoals
  EXPLORE  (steps 1..N-2)  alternate EXPAND_NODE then NOTE/CONCLUDE
  CLOSE    (last steps)    CONCLUDE gaps, then FINALIZE_ANSWER

Hard rules (enforced by the executor — violations waste the step):
  - Pick only from "Available actions this phase".
  - EXPAND_NODE: node_id must be in the Unexpanded frontier list.
  - PLAN: 2-4 short imperative phrases.
  - CONCLUDE: plan_step is REQUIRED.
  - FINALIZE_ANSWER: args MUST be exactly {{}} (empty). The final answer is
    composed deterministically from your grounded conclusions — do NOT
    embed answer text in args (no text, no text_psN, no body). Just emit
    {{"action": "FINALIZE_ANSWER", "args": {{}}}}.

Support selection (applies to NOTE and CONCLUDE):
  - supports = 1 to 4 ids. NEVER dump everything visible.
  - Pick the MOST relevant 1-4 ids from "Candidate supports". The list is
    ranked by relevance — top items are best. Higher score is better.
  - VALID support types: evidence, note, conclusion.
  - NEVER cite plan_step ids (ps_*) as supports. Plan steps organize
    reasoning; they are not evidence. Use the `plan_step` arg for those.
  - NEVER cite the question (Q0) as a support.
  - At least one transitive ancestor of every cited support must be raw
    evidence — chained notes/conclusions are fine, free-floating claims
    are rejected.
  - If two candidate supports are linked by a contradict edge, use
    VERIFY_EDGE FIRST to resolve which one to trust.
  - support_usage is REQUIRED. For each id in supports, write a short
    string describing the SPECIFIC content you extracted from that node.
    Example:
        supports: ["sound_requires_material_medium"]
        support_usage: {{"sound_requires_material_medium":
                        "sound needs particle interactions in a medium"}}
    The keys must EXACTLY equal the supports list. If you cannot honestly
    write a usage string for a support id, do not cite it.

Misconception nodes (tagged [MISCONCEPTION] in the briefing, suffix
`_false` in their id) carry text bodies that state the WRONG view. Do
NOT cite the body text as evidence of the truth. If you need to refute
the misconception, pair the misconception node with the correct
counterpart (e.g. `sound_travels_in_vacuum_false` paired with
`sound_requires_material_medium`) and explicitly write that the
misconception is wrong in the conclusion text.

Code/implementation steps: If a plan_step asks for code, implementation,
syntax, or "show how to ..." — and a candidate support has the suffix
`_apply` and contains real code (e.g. `cpp_kadane_template_apply`,
`py_dijkstra_apply`) — you MUST cite that `_apply` node in the
NOTE/CONCLUDE for that plan_step. The reader needs the authoritative
source, not just your paraphrase. The readout automatically surfaces
cited code-bearing nodes as fenced blocks, so citing the `_apply` node
is what makes the actual code appear in the final answer.

Pacing: aim for 1-2 EXPAND_NODEs per plan_step then CONCLUDE that plan_step. The focus advances automatically once a plan_step has one grounded conclusion.

## Tools
{tool_descriptions}

Output EXACTLY one JSON object with these 3 keys (no surrounding prose, no markdown):
  thought_summary  — VERY BRIEF (<= 25 words) why-this-action note
  action           — one of the ActionType values
  args             — object with the action's required arguments
"""


# Grammar-constrained schema for response_format.
#
# Stage A token-trim (2026-05-17): dropped `reason` (duplicative with
# thought_summary and never used downstream), tightened thought_summary
# from 400 -> 160 chars (~25 words). The `action` enum is narrowed per
# turn to only the phase's valid actions so the model is grammar-
# forbidden from emitting an out-of-phase choice.
JSON_ACTION_SCHEMA: Dict[str, Any] = {
    "type": "object",
    "properties": {
        "thought_summary": {"type": "string", "maxLength": 160},
        "action": {"type": "string", "enum": [a.value for a in ActionType]},
        "args": {"type": "object"},
    },
    "required": ["thought_summary", "action", "args"],
    "additionalProperties": False,
}


# ---------------------------------------------------------------------------
# LlamaServerController — talks to a local llama.cpp server over HTTP.
#
# Why this and not in-process llama-cpp-python:
#   - model stays loaded between Python invocations (huge for iteration)
#   - survives Python crashes
#   - swap backends (llama.cpp, vLLM, ollama) without touching this code
#
# Start the server first (separate terminal):
#   llama-server -m cache/models/GLM-4.7-Flash-Q2_K.gguf \
#                -ngl 20 -c 4096 --host 127.0.0.1 --port 6767
#
# Hard rules: localhost only, no API key, no SSL — this controller will
# refuse to talk to non-loopback hosts.
# ---------------------------------------------------------------------------

DEFAULT_LLAMA_SERVER_URL = "http://127.0.0.1:6767"

# Pre-action shortcut threshold: skip the LLM call after a successful PLAN
# when the top-priority frontier item is strictly greater than #2. Anchor
# priorities come from lexical_overlap of question vs node text and sit in
# tight clusters (~0.05 spread for 8 topical anchors), so we only require
# a non-tie. Auto-expanding the top anchor is always reversible — the
# model can EXPAND_NODE the others on subsequent turns.
AUTO_EXPAND_MARGIN = 1e-6


@dataclass
class LlamaServerConfig:
    base_url: str = DEFAULT_LLAMA_SERVER_URL
    temperature: float = 0.3
    max_tokens: int = 512
    timeout: float = 240.0   # generous; Q2_K @ 20 GPU layers can be slow
    auto_actions: bool = True   # enable PLAN->EXPAND_NODE shortcut (Tier 1 v1)


class LlamaServerController(Controller):
    # Circuit breaker: if the model emits unparseable JSON this many times
    # in a row, abort the run with a RuntimeError. Prevents the runaway
    # loop we saw on modexp where each parse_failed turn cost a full
    # max_tokens generation, racking up 28000s before finally exhausting
    # the adaptive step budget.
    MAX_CONSECUTIVE_PARSE_FAILURES: int = 3

    def __init__(self, config: Optional[LlamaServerConfig] = None) -> None:
        self.config = config or LlamaServerConfig()
        self._checked = False
        self._conversation_history: List[Dict[str, Any]] = []
        self._expanded_nodes: Set[str] = set()
        self._last_action_result: str = ""
        self._last_action_type: Optional[ActionType] = None
        self._auto_action_count: int = 0  # counted across one query
        self._consecutive_parse_failures: int = 0
        self._guard_localhost(self.config.base_url)

    @staticmethod
    def _guard_localhost(url: str) -> None:
        """Refuse anything that isn't loopback. No accidental remote hits."""
        from urllib.parse import urlparse
        host = (urlparse(url).hostname or "").lower()
        if host not in ("127.0.0.1", "localhost", "::1"):
            raise ValueError(
                f"LlamaServerController refuses non-localhost base_url "
                f"({url!r}). Use 127.0.0.1 or localhost only."
            )

    @property
    def name(self) -> str:
        return f"LlamaServer({self.config.base_url})"

    def _build_system_prompt(self) -> str:
        tool_texts = [f"- {a.value}: {desc}" for a, desc in TOOL_DESCRIPTIONS.items()]
        return GLM_SYSTEM_PROMPT.format(tool_descriptions="\n".join(tool_texts))

    def _ensure_server_reachable(self) -> None:
        """Hit /health once per process to fail fast with a useful message."""
        if self._checked:
            return
        import urllib.request
        import urllib.error
        url = self.config.base_url.rstrip("/") + "/health"
        try:
            with urllib.request.urlopen(url, timeout=5) as resp:
                _ = resp.read(64)  # don't care what it returns; reachable is enough
            self._checked = True
        except (urllib.error.URLError, OSError) as e:
            raise RuntimeError(
                f"llama-server unreachable at {self.config.base_url!r}. "
                f"Start it with:\n"
                f"  llama-server -m cache/models/GLM-4.7-Flash-Q2_K.gguf "
                f"-ngl 20 -c 4096 --host 127.0.0.1 --port 6767\n"
                f"Underlying error: {e}"
            )

    def _post_chat(self, messages: List[Dict[str, Any]], schema: Dict[str, Any]) -> Dict[str, Any]:
        import urllib.request
        import urllib.error
        self._ensure_server_reachable()
        payload = json.dumps({
            "messages": messages,
            "temperature": self.config.temperature,
            "max_tokens": self.config.max_tokens,
            # OpenAI-compatible JSON-Schema grammar (llama.cpp converts to
            # GBNF under the hood). Same shape llama-cpp-python uses.
            "response_format": {"type": "json_object", "schema": schema},
            # GLM-4.7-Flash has reasoning/thinking mode enabled in its
            # chat template by default. With thinking on, the model emits
            # a <think>...</think> block BEFORE the answer, which eats
            # the entire max_tokens budget on every turn and starves the
            # JSON output. We need the structured action, not the trace,
            # so disable thinking explicitly.
            "chat_template_kwargs": {"enable_thinking": False},
            "reasoning_effort": "none",  # newer llama.cpp builds honor this too
            # Reuse prompt prefix across requests — much cheaper.
            "cache_prompt": True,
        }).encode("utf-8")
        url = self.config.base_url.rstrip("/") + "/v1/chat/completions"
        req = urllib.request.Request(
            url, data=payload,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        try:
            with urllib.request.urlopen(req, timeout=self.config.timeout) as resp:
                return json.loads(resp.read().decode("utf-8"))
        except urllib.error.HTTPError as e:
            body = e.read().decode("utf-8", errors="replace")[:500]
            raise RuntimeError(
                f"llama-server HTTP {e.code} on /v1/chat/completions: {body}"
            )

    def _try_auto_action(
        self,
        session: SessionGraph,
        phase: Phase,
        valid_actions: Set[ActionType],
        last_error: Optional[Dict[str, str]],
    ) -> Optional[Action]:
        """Return a deterministic Action when the next step is unambiguous,
        else None. Each successful return saves one LLM round-trip.

        v1 covers a single pattern: right after a successful PLAN, if the
        unexpanded frontier has a clear winner (priority margin >=
        AUTO_EXPAND_MARGIN over #2), auto-emit EXPAND_NODE on it. Skipped
        when the model just failed (let it adapt to its own error) or when
        EXPAND_NODE isn't in valid_actions for the current phase.
        """
        if not self.config.auto_actions:
            return None
        if last_error is not None:
            return None
        if self._last_action_type != ActionType.PLAN:
            return None
        if phase != Phase.EXPLORE:
            return None
        if ActionType.EXPAND_NODE not in valid_actions:
            return None

        candidates = [
            f for f in session.frontier
            if f.item_type == "expand_node"
            and f.node_id
            and f.node_id not in self._expanded_nodes
        ]
        if not candidates:
            return None
        candidates.sort(key=lambda f: -f.priority)
        top = candidates[0]
        second = candidates[1].priority if len(candidates) >= 2 else 0.0
        margin = top.priority - second
        if margin < AUTO_EXPAND_MARGIN:
            return None

        return Action(
            ActionType.EXPAND_NODE,
            {"node_id": top.node_id},
            f"auto: post-PLAN expand top frontier (priority={top.priority:.2f}, margin={margin:.2f})",
        )

    def choose_action(
        self,
        question: str,
        session: SessionGraph,
        step: int,
        max_steps: int,
        phase: Phase,
        valid_actions: Set[ActionType],
        last_error: Optional[Dict[str, str]] = None,
    ) -> Action:
        if step == 0:
            self._expanded_nodes.clear()
            self._conversation_history.clear()
            self._last_action_result = ""
            self._last_action_type = None
            self._auto_action_count = 0
            self._consecutive_parse_failures = 0

        # Tier-1 v1 chaining: skip the LLM call when the next action is
        # deterministically obvious. Currently covers ONE pattern, the
        # PLAN->EXPAND_NODE chain on the top-priority frontier item.
        # Returns None when conditions aren't met so we fall back to LLM.
        shortcut = self._try_auto_action(session, phase, valid_actions, last_error)
        if shortcut is not None:
            self._auto_action_count += 1
            return shortcut

        briefing = build_briefing(
            question, session, phase, step, max_steps, valid_actions, last_error,
            role_aware=getattr(session, "_role_aware", False),
        )

        messages: List[Dict[str, Any]] = [
            {"role": "system", "content": self._build_system_prompt()},
        ]
        # Keep the last turn only — Q2_K parrots prior outputs when given
        # more history. The briefing already carries all state we need.
        for msg in self._conversation_history[-2:]:
            messages.append(msg)
        messages.append({"role": "user", "content": briefing})

        # Narrow the action enum to ONLY the phase's valid actions so the
        # model is grammar-forbidden from emitting an out-of-phase choice.
        # Also constrain args.text minLength=1 (when present): NOTE and
        # CONCLUDE require text; PLAN/EXPAND_NODE/etc. simply omit it.
        # This eliminates the empty_text wasted-step failures we saw in
        # Stage A v2 traces without affecting actions that don't need text.
        turn_schema = dict(JSON_ACTION_SCHEMA)
        turn_schema["properties"] = dict(JSON_ACTION_SCHEMA["properties"])
        turn_schema["properties"]["action"] = {
            "type": "string",
            "enum": sorted(a.value for a in valid_actions) or [ActionType.STOP.value],
        }
        turn_schema["properties"]["args"] = {
            "type": "object",
            "properties": {
                "text": {"type": "string", "minLength": 1, "maxLength": 600},
                "supports": {
                    "type": "array",
                    "items": {"type": "string"},
                    "maxItems": SUPPORTS_MAX,
                },
            },
            "additionalProperties": True,
        }
        response = self._post_chat(messages, turn_schema)

        try:
            content = response["choices"][0]["message"]["content"].strip()
        except (KeyError, IndexError) as e:
            raise RuntimeError(f"unexpected llama-server response shape: {e}; got {response!r}")

        try:
            parsed = json.loads(content)
        except json.JSONDecodeError:
            self._consecutive_parse_failures += 1
            print(
                f"  [LlamaServer] JSON parse failed "
                f"(#{self._consecutive_parse_failures} consecutive); "
                f"raw[:200]={content[:200]!r}"
            )
            if self._consecutive_parse_failures >= self.MAX_CONSECUTIVE_PARSE_FAILURES:
                raise RuntimeError(
                    f"model stuck in parse-failure loop "
                    f"({self._consecutive_parse_failures} consecutive parse_failed). "
                    f"Last raw output[:200]={content[:200]!r}. "
                    f"This usually means args.text exceeded grammar maxLength or "
                    f"max_tokens={self.config.max_tokens} truncated the JSON mid-string."
                )
            self._conversation_history.append({"role": "assistant", "content": content})
            return Action(ActionType.STOP, {}, "parse_failed")

        # Successful parse — reset the failure counter.
        self._consecutive_parse_failures = 0

        action = Action.from_dict(parsed)

        # If the model picks an out-of-phase action, leave the validation to
        # the main loop — it will record the error and surface it on the next
        # turn. We DO repair invalid EXPAND_NODE node_ids because that's an
        # arg-shape issue, not a phase/protocol issue.
        if action.action_type == ActionType.EXPAND_NODE:
            nid = str(action.args.get("node_id", "")).strip()
            unexpanded = [
                f.node_id for f in session.frontier
                if f.item_type == "expand_node" and f.node_id and f.node_id not in self._expanded_nodes
            ]
            if nid not in unexpanded and unexpanded:
                action = Action(
                    ActionType.EXPAND_NODE,
                    {"node_id": unexpanded[0]},
                    f"corrected from {nid!r} to {unexpanded[0]!r} (not in frontier)",
                )

        self._conversation_history.append({"role": "assistant", "content": content})
        self._conversation_history.append({
            "role": "user",
            "content": json.dumps({"step": step, "action": action.action_type.value}),
        })
        return action

    def note_result(self, action: Action, result: ActionResult) -> None:
        if action.action_type == ActionType.EXPAND_NODE and result.success:
            nid = str(action.args.get("node_id", "")).strip()
            if nid:
                self._expanded_nodes.add(nid)
        if result.success:
            self._last_action_result = (
                f"{action.action_type.value} OK: +{result.new_nodes} nodes, "
                f"+{result.new_edges} edges, +{result.new_paths} paths"
            )
            self._last_action_type = action.action_type
        else:
            self._last_action_result = (
                f"{action.action_type.value} FAIL: {result.error} — {result.summary}"
            )
            # Leave _last_action_type untouched on failure so the chaining
            # gate keeps treating the last *successful* action as the trigger.
        # Feed the outcome back into the next turn so the model can adapt.
        self._conversation_history.append({
            "role": "user",
            "content": json.dumps({"step_result": self._last_action_result}),
        })


# ---------------------------------------------------------------------------
# Main loop
# ---------------------------------------------------------------------------

def answer_query_v2_with_session(
    question: str,
    graph: MemoryGraph,
    controller: Controller,
    pred_model: Any = None,
    pred_device: Optional[torch.device] = None,
    max_steps: int = MAX_STEPS,
    k_anchors: int = 8,
    anchor_strategy: str = "topk",
    graph_basename: str = "graph",
    role_aware: bool = False,
) -> Tuple[SessionGraph, AnswerPacket, List[Dict[str, Any]]]:
    """Same as answer_query_v2 but also returns the final session graph and
    the structured action trace, for evaluation harnesses that need to
    inspect graph metrics (path depth, support coverage, contradictions).
    """
    packet, session, trace = _answer_query_v2_core(
        question, graph, controller, pred_model, pred_device, max_steps, k_anchors,
        anchor_strategy=anchor_strategy, graph_basename=graph_basename,
        role_aware=role_aware,
    )
    return session, packet, trace


def answer_query_v2(
    question: str,
    graph: MemoryGraph,
    controller: Controller,
    pred_model: Any = None,
    pred_device: Optional[torch.device] = None,
    max_steps: int = MAX_STEPS,
    k_anchors: int = 8,
    anchor_strategy: str = "topk",
    graph_basename: str = "graph",
    role_aware: bool = False,
) -> AnswerPacket:
    packet, _, _ = _answer_query_v2_core(
        question, graph, controller, pred_model, pred_device, max_steps, k_anchors,
        anchor_strategy=anchor_strategy, graph_basename=graph_basename,
        role_aware=role_aware,
    )
    return packet


def _answer_query_v2_core(
    question: str,
    graph: MemoryGraph,
    controller: Controller,
    pred_model: Any,
    pred_device: Optional[torch.device],
    max_steps: int,
    k_anchors: int,
    *,
    anchor_strategy: str = "topk",
    graph_basename: str = "graph",
    role_aware: bool = False,
) -> Tuple[AnswerPacket, SessionGraph, List[Dict[str, Any]]]:
    session = SessionGraph(question)
    # Stash role_aware on the session so the controller's choose_action
    # can pass it to build_briefing without changing the Controller ABC
    # signature. Stage 3 opt-in.
    session._role_aware = role_aware  # type: ignore[attr-defined]
    if anchor_strategy == "legacy":
        anchors = retrieve_anchors_legacy(question, graph, k=k_anchors)
    else:
        anchors = retrieve_anchors_v2(
            question, graph, k=k_anchors,
            strategy=anchor_strategy, graph_basename=graph_basename,
        )
    session.import_memory_nodes(anchors, graph)
    # Pull in any main-graph edges between anchors so contradict/support
    # relations between them are visible before the first model turn.
    _import_missing_edges(session, graph)
    init_frontier_from_anchors(session, anchors)
    if pred_model is not None and pred_device is not None:
        memory_ids = [
            n.source_memory_id for n in session.nodes.values()
            if n.node_type == NODE_EVIDENCE and n.source_memory_id
        ][:8]
        run_pred_and_apply(session, pred_model, question, memory_ids, graph, pred_device)

    action_trace: List[Dict[str, Any]] = []
    last_error: Optional[Dict[str, str]] = None
    last_action_type: Optional[ActionType] = None
    finalized = False
    pred_available = pred_model is not None and pred_device is not None

    # Budget handling. max_steps == 0 is the sentinel for "adaptive":
    # start with a generous bound, then resize after PLAN based on the
    # model's actual plan size. Any other value is honored as-is so
    # callers retain full control (testing, hand-tuning, etc).
    adaptive_mode = (max_steps == 0)
    effective_max_steps = 24 if adaptive_mode else max_steps

    step = 0
    while step < effective_max_steps:
        session.step = step
        phase = compute_phase(step, effective_max_steps)
        valid = valid_actions_for_phase(
            phase, session,
            step=step, max_steps=effective_max_steps,
            last_action_type=last_action_type,
            pred_available=pred_available,
        )

        action = controller.choose_action(
            question, session, step, effective_max_steps, phase, valid, last_error,
        )
        entry: Dict[str, Any] = {
            "step": step,
            "phase": phase.value,
            "action": action.action_type.value,
            "args": action.args,
            "thought": action.thought_summary,
        }

        # Out-of-phase rejection
        if action.action_type not in valid:
            err = {
                "action": action.action_type.value,
                "reason": f"out_of_phase: {action.action_type.value} not valid in phase {phase.value} (allowed: {sorted(a.value for a in valid)})",
            }
            entry["result"] = {"success": False, "error": "out_of_phase", "summary": err["reason"]}
            last_error = err
            controller.note_result(action, ActionResult(action, False, summary=err["reason"], error="out_of_phase"))
            action_trace.append(entry)
            step += 1
            continue

        # Loop-handled actions
        if action.action_type == ActionType.FINALIZE_ANSWER:
            entry["result"] = {"success": True, "summary": "finalizing"}
            action_trace.append(entry)
            finalized = True
            break
        if action.action_type == ActionType.STOP:
            entry["result"] = {"success": True, "summary": "stop"}
            action_trace.append(entry)
            break

        # Execute via the dispatch table
        result = execute_action(action, session, graph, pred_model, pred_device)
        controller.note_result(action, result)
        entry["result"] = result.to_dict()
        action_trace.append(entry)
        last_error = None if result.success else {
            "action": action.action_type.value,
            "reason": f"{result.error}: {result.summary}",
        }
        last_action_type = action.action_type if result.success else last_action_type

        # Adaptive resize: once PLAN has succeeded, scale the budget to
        # match the plan size the model actually wrote. Only happens once,
        # and only when the caller asked for adaptive (max_steps=0).
        if (
            adaptive_mode
            and step == 0
            and action.action_type == ActionType.PLAN
            and result.success
        ):
            plan_size = len(get_plan_steps(session))
            if plan_size > 0:
                new_budget = adaptive_max_steps(plan_size)
                if new_budget != effective_max_steps:
                    effective_max_steps = new_budget
                    entry["budget_resized_to"] = new_budget  # surface in trace

        step += 1

    # Compose the answer deterministically from the graph
    answer_text = compose_graph_readout(session)

    _save_action_trace(question, action_trace, answer_text, finalized=finalized)

    # Build the AnswerPacket. Evidence paths are derived from session paths
    # for diagnostic continuity with v1; the answer itself comes from the
    # graph readout, not from the paths.
    all_paths = find_all_paths_from_question(session, max_depth=PATH_DEPTH_LIMIT)
    for p in all_paths:
        if p.path_id not in session.paths:
            session.add_path(p)
    all_paths = rank_paths(all_paths, question, session)
    contradictions = find_contradictions_on_paths(session, all_paths)

    cov = plan_step_coverage(session)
    confidence = (
        sum(row["done"] for row in cov) / len(cov) if cov else 0.0
    )

    evidence_data: List[Dict[str, Any]] = []
    for p in all_paths[:3]:
        evidence_data.append({
            "path_id": p.path_id,
            "type": p.path_type,
            "confidence": p.confidence,
            "score": p.score,
            "nodes": p.node_ids,
            "edges": [(s, d, r) for s, d, r in p.edges],
            "texts": p.evidence_texts,
        })

    packet = AnswerPacket(
        question=question,
        answer=answer_text,
        confidence=confidence,
        path_count=len(all_paths[:3]),
        evidence_paths=evidence_data,
        contradictions_found=len(contradictions),
        steps_taken=session.step,
        answer_type=classify_question_type(question),
    )
    return packet, session, action_trace


def _save_action_trace(
    question: str,
    trace: List[Dict[str, Any]],
    answer: str,
    *,
    finalized: bool = False,
) -> None:
    os.makedirs("artifacts", exist_ok=True)
    stamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S_%f")
    path = f"artifacts/trace_{stamp}_{uuid.uuid4().hex[:6]}.json"
    with open(path, "w", encoding="utf-8") as f:
        json.dump(
            {
                "question": question,
                "finalized": finalized,
                "trace": trace,
                "answer": answer[:1000],
            },
            f, ensure_ascii=False, indent=2,
        )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    import argparse
    parser = argparse.ArgumentParser(
        description=(
            "Answerer-v2: graph-reasoning over a local GLM via llama-server. "
            "Start the server in a separate terminal before --controller server: "
            "llama-server -m cache/models/GLM-4.7-Flash-Q2_K.gguf -ngl 20 -c 4096 "
            "--host 127.0.0.1 --port 6767"
        )
    )
    parser.add_argument("--question", type=str, required=True)
    parser.add_argument("--graph", type=str, required=True, help="Path to graph JSON")
    parser.add_argument("--controller", type=str, default="mock", choices=["mock", "server"])
    parser.add_argument("--max-steps", type=int, default=MAX_STEPS,
                        help="0 = adaptive (auto-sized after PLAN by plan length); otherwise honored as the hard cap")
    parser.add_argument("--k-anchors", type=int, default=8)
    parser.add_argument("--server-url", default=DEFAULT_LLAMA_SERVER_URL,
                        help=f"llama-server base url (default {DEFAULT_LLAMA_SERVER_URL})")
    parser.add_argument("--temperature", type=float, default=0.3)
    parser.add_argument("--max-tokens", type=int, default=512)
    parser.add_argument("--output", type=str, default=None, help="Output JSON path")
    args = parser.parse_args()

    graph = MemoryGraph.load_json(args.graph)
    print(f"Loaded graph: {len(graph.nodes)} nodes, {len(graph.edges)} edges")
    print(f"Question: {args.question}")
    print(f"Controller: {args.controller}")

    if args.controller == "server":
        controller: Controller = LlamaServerController(LlamaServerConfig(
            base_url=args.server_url,
            temperature=args.temperature,
            max_tokens=args.max_tokens,
        ))
    else:
        controller = MockController()

    packet = answer_query_v2(
        question=args.question,
        graph=graph,
        controller=controller,
        max_steps=args.max_steps,
        k_anchors=args.k_anchors,
    )

    print("\n" + "=" * 60)
    print(f"Answer (type={packet.answer_type}, conf={packet.confidence:.3f})")
    print("=" * 60)
    print(packet.answer)
    print("=" * 60)
    print(f"Steps: {packet.steps_taken}, Paths: {packet.path_count}, Contradictions: {packet.contradictions_found}")

    if args.output:
        output = {
            "question": args.question,
            "answer": packet.answer,
            "confidence": packet.confidence,
            "answer_type": packet.answer_type,
            "steps_taken": packet.steps_taken,
            "path_count": packet.path_count,
            "contradictions_found": packet.contradictions_found,
            "evidence_paths": packet.evidence_paths,
        }
        Path(args.output).write_text(json.dumps(output, indent=2, ensure_ascii=False), encoding="utf-8")
        print(f"\nOutput saved to {args.output}")


if __name__ == "__main__":
    main()
