"""Expand data/question_bank.json with ~200 more hand-authored questions.

Appends to the existing bank, de-dups by question text, renumbers ids. Domains
match merged_graph (physics/chem/bio/math/cs/algo/logic/sysdesign). Idempotent.
"""
import json, os

STEPS = {"easy": 4, "medium": 6, "hard": 8, "extreme": 10}

# (domain, difficulty, question)
NEW = [
 # ---- physics ----
 ("physics","easy","What is inertia and how does it relate to mass?"),
 ("physics","easy","Why does a heavier object not fall faster than a lighter one in vacuum?"),
 ("physics","medium","Explain conservation of momentum using a collision example."),
 ("physics","medium","Why does a diver tuck into a ball to spin faster?"),
 ("physics","medium","What is the difference between speed and velocity?"),
 ("physics","medium","Why does a capacitor block DC but pass AC?"),
 ("physics","medium","Explain why a ball thrown upward decelerates then accelerates downward."),
 ("physics","hard","Why does the photoelectric effect require a minimum frequency, not just intensity?"),
 ("physics","hard","Explain why entropy tends to increase in an isolated system."),
 ("physics","hard","Why does a blackbody emit a continuous spectrum that shifts with temperature?"),
 ("physics","hard","How does resonance amplify oscillations at a natural frequency?"),
 ("physics","medium","What determines the escape velocity of a planet?"),
 ("physics","medium","Why does pressure increase with depth in a fluid?"),
 ("physics","easy","What is the difference between conduction, convection, and radiation?"),
 ("physics","hard","Why can no information travel faster than light?"),
 # ---- chemistry ----
 ("chem","easy","What is a catalyst and how does it affect a reaction?"),
 ("chem","medium","How does a buffer solution resist changes in pH?"),
 ("chem","medium","What happens at the atomic level during oxidation and reduction?"),
 ("chem","easy","What is a mole in chemistry and why is it useful?"),
 ("chem","medium","How does electronegativity change across a period of the periodic table?"),
 ("chem","easy","What are isotopes and how do they differ from each other?"),
 ("chem","medium","Why is activation energy required even for exothermic reactions?"),
 ("chem","medium","What does the ideal gas law relate and when does it break down?"),
 ("chem","hard","Why does increasing pressure shift the Haber-process equilibrium toward ammonia?"),
 ("chem","easy","What is the difference between a physical and a chemical change?"),
 ("chem","medium","Why do metals conduct electricity?"),
 # ---- biology ----
 ("bio","easy","What is osmosis and which way does water move?"),
 ("bio","medium","Summarize how photosynthesis converts light into chemical energy."),
 ("bio","hard","How does an action potential propagate along a neuron?"),
 ("bio","medium","What is the difference between mitosis and meiosis?"),
 ("bio","medium","How does the immune system remember a pathogen after infection?"),
 ("bio","hard","Why does protein function depend on its three-dimensional folding?"),
 ("bio","easy","What is homeostasis and give one example in the human body."),
 ("bio","medium","How do dominant and recessive alleles determine a trait?"),
 ("bio","medium","Why does energy decrease at each level of a food chain?"),
 ("bio","hard","How does CRISPR-Cas9 target and edit a specific DNA sequence?"),
 ("bio","easy","What is the difference between prokaryotic and eukaryotic cells?"),
 # ---- math ----
 ("math","easy","What does a limit describe in calculus?"),
 ("math","medium","What does a definite integral represent?"),
 ("math","medium","Why is the product of two negative numbers positive?"),
 ("math","hard","Prove that the square root of 2 is irrational."),
 ("math","medium","What is modular arithmetic and where is it used?"),
 ("math","medium","Explain the principle of mathematical induction."),
 ("math","easy","What is the difference between the dot product and the cross product?"),
 ("math","medium","When are two events statistically independent?"),
 ("math","medium","What does the expected value of a random variable mean?"),
 ("math","easy","Why is log(ab) = log a + log b?"),
 ("math","hard","What does the determinant of a matrix tell you geometrically?"),
 ("math","medium","How does the Euclidean algorithm find the GCD of two numbers?"),
 ("math","hard","Use stars and bars to count nonnegative integer solutions of x+y+z=10."),
 ("math","medium","What does the chain rule compute and why is it needed?"),
 ("math","extreme","Explain intuitively why a Taylor series approximates a function locally."),
 # ---- cs ----
 ("cs","easy","What is the difference between recursion and iteration?"),
 ("cs","medium","What is a pointer and what problems can misusing one cause?"),
 ("cs","medium","Why does immutability simplify reasoning about concurrent code?"),
 ("cs","medium","What is database normalization and what does it prevent?"),
 ("cs","medium","What tradeoff does adding a database index introduce?"),
 ("cs","hard","How does a race condition arise and how does a mutex prevent it?"),
 ("cs","medium","What is the difference between a mutex and a semaphore?"),
 ("cs","easy","What is the difference between big-endian and little-endian?"),
 ("cs","medium","Why does UTF-8 use a variable number of bytes per character?"),
 ("cs","easy","What is the difference between a compiler and a linker?"),
 ("cs","medium","What causes a stack overflow in a program?"),
 ("cs","medium","What is a memory leak and how does it differ in GC vs non-GC languages?"),
 ("cs","easy","What is the difference between pass-by-value and pass-by-reference?"),
 ("cs","hard","How does CPU branch prediction speed up execution and when does it hurt?"),
 ("cs","medium","Why is premature optimization discouraged?"),
 # ---- algorithms ----
 ("algo","medium","When is the two-pointer technique applicable to an array problem?"),
 ("algo","medium","What problem does a sliding window solve efficiently?"),
 ("algo","hard","When does A* search outperform Dijkstra, and what does the heuristic require?"),
 ("algo","hard","What does a segment tree support that a prefix-sum array cannot?"),
 ("algo","hard","How does the KMP algorithm avoid re-scanning characters during string search?"),
 ("algo","medium","How does a binary heap support O(log n) insert and extract-min?"),
 ("algo","hard","How does quickselect find the k-th smallest element in average O(n)?"),
 ("algo","medium","When can counting sort beat comparison sorts, and what is its limitation?"),
 ("algo","medium","What is a trie and when is it preferable to a hash map?"),
 ("algo","hard","How does backtracking prune the search space in constraint problems?"),
 ("algo","extreme","When is bitmask dynamic programming the right tool, and what bounds its size?"),
 ("algo","easy","Why is appending to a dynamic array amortized O(1)?"),
 ("algo","medium","What is the difference between stable and unstable sorting?"),
 ("algo","hard","How does matrix exponentiation compute the n-th Fibonacci number in O(log n)?"),
 ("algo","medium","Why does breadth-first search find the shortest path in an unweighted graph?"),
 # ---- logic ----
 ("logic","easy","State modus ponens with an example."),
 ("logic","medium","What is modus tollens and how does it differ from affirming the consequent?"),
 ("logic","medium","Apply De Morgan's laws to negate 'A and B'."),
 ("logic","medium","What is a vacuously true statement?"),
 ("logic","medium","What is the difference between inductive and deductive reasoning?"),
 ("logic","hard","Explain the structure of a proof by contradiction."),
 ("logic","easy","What does a biconditional 'A if and only if B' assert?"),
 ("logic","medium","Why is 'affirming the consequent' a logical fallacy?"),
 ("logic","hard","Why does a single counterexample refute a universal claim but not an existential one?"),
 ("logic","medium","What is the converse of a conditional and why is it not equivalent?"),
 # ---- systems design ----
 ("sysdesign","medium","Compare token-bucket and leaky-bucket rate limiting."),
 ("sysdesign","medium","What problem does a CDN solve and how?"),
 ("sysdesign","medium","Compare write-through and write-back caching."),
 ("sysdesign","hard","How does leader election work in a distributed system, and why is it needed?"),
 ("sysdesign","hard","What is a quorum and how does it ensure consistency across replicas?"),
 ("sysdesign","medium","How do idempotency keys prevent duplicate side effects on retries?"),
 ("sysdesign","hard","What does a circuit breaker protect against and how does it behave?"),
 ("sysdesign","medium","When is a Bloom filter the right data structure in a system?"),
 ("sysdesign","hard","What is a hot-key problem and how can you mitigate it?"),
 ("sysdesign","medium","What is fan-out on write vs fan-out on read in a feed system?"),
 ("sysdesign","extreme","Why is exactly-once delivery hard, and what do systems do instead?"),
 ("sysdesign","medium","Why might you denormalize data in a high-read system?"),
 ("sysdesign","hard","How does optimistic concurrency control detect conflicting writes?"),
 ("sysdesign","medium","What is the purpose of a heartbeat in a distributed cluster?"),
 ("sysdesign","hard","How does a log-structured merge tree make writes fast?"),
 # ---- earth/astro/other reasoning ----
 ("physics","medium","Why do we always see the same side of the Moon from Earth?"),
 ("physics","hard","Why does a gyroscope resist changes to its orientation?"),
 ("chem","medium","Why does salt lower the freezing point of water?"),
 ("bio","medium","Why do red blood cells lack a nucleus in humans?"),
 ("math","medium","Why does the Monty Hall strategy of switching win 2/3 of the time?"),
 ("cs","medium","Why is hashing passwords with a salt better than hashing alone?"),
 ("algo","medium","Why does memoized Fibonacci run in O(n) instead of exponential time?"),
 ("logic","medium","Is 'all swans are white' falsifiable, and what would falsify it?"),
 ("sysdesign","medium","Why can adding more servers fail to linearly increase throughput?"),
 ("physics","easy","Why does a metal spoon feel colder than a wooden one at the same temperature?"),
 ("chem","hard","Why do noble gases rarely form chemical bonds?"),
 ("bio","hard","How does antibiotic resistance spread through a bacterial population?"),
 ("math","hard","Why does 0.999... equal exactly 1?"),
 ("cs","hard","Why is the halting problem undecidable, in intuitive terms?"),
 ("algo","extreme","How does Floyd's cycle-detection (tortoise and hare) find a loop in O(1) space?"),
 ("logic","hard","Why can a valid argument still have a false conclusion?"),
 ("sysdesign","extreme","How would you design a globally consistent counter with high write throughput?"),
 ("physics","medium","Why does a rainbow form, and why is it always opposite the sun?"),
 ("chem","medium","Why does iron rust faster in salty, humid air?"),
 ("bio","medium","Why does exercise increase the body's demand for oxygen?"),
 ("math","easy","What is the difference between mean, median, and mode?"),
 ("cs","medium","Why is JSON not a good format for very large numeric datasets?"),
 ("algo","hard","Why does Kruskal's algorithm need a union-find structure?"),
 ("logic","easy","What is the negation of 'some cats are black'?"),
 ("sysdesign","medium","Why is a single global lock a scalability bottleneck?"),
 ("physics","hard","Why does a superconductor expel magnetic fields (Meissner effect)?"),
 ("chem","easy","What is the difference between an atom and a molecule?"),
 ("bio","medium","How does natural selection differ from genetic drift?"),
 ("math","medium","Why is the empty set a subset of every set?"),
 ("cs","medium","Why does TCP use a three-way handshake?"),
 ("algo","medium","Why does Dijkstra fail with negative edge weights?"),
 ("logic","medium","What is the contrapositive of 'if n is even then n^2 is even'?"),
 ("sysdesign","hard","How does sharding by hash differ from sharding by range, in tradeoffs?"),
 ("physics","medium","Why does sound travel faster in water than in air?"),
 ("chem","medium","Why is graphite a conductor but diamond an insulator?"),
 ("bio","easy","What is the function of the cell membrane?"),
 ("math","hard","Why are there infinitely many twin-prime candidates but no proof yet?"),
 ("cs","easy","What is the difference between RAM and a hard disk?"),
 ("algo","medium","Why is binary search O(log n) and not O(n)?"),
 ("logic","medium","Why is 'this statement is false' paradoxical?"),
 ("sysdesign","medium","What is eventual vs strong consistency, with a use case for each?"),
 ("physics","extreme","Why does quantum entanglement not allow faster-than-light signaling?"),
 ("chem","hard","Why does adding a common ion decrease a salt's solubility?"),
 ("bio","hard","Why do mitochondria have their own DNA?"),
 ("math","extreme","Why does the diagonal argument show the reals are uncountable?"),
 ("cs","hard","Why does double-checked locking need memory barriers to be correct?"),
 ("algo","hard","How does topological sort enable scheduling tasks with dependencies?"),
 ("logic","hard","What distinguishes a necessary condition from a sufficient one, formally?"),
 ("sysdesign","hard","Why does the CAP theorem force a choice only during a network partition?"),
 ("physics","medium","Why does ice skating work — why is the ice slippery?"),
 ("chem","medium","Why does a reaction reach equilibrium rather than going to completion?"),
 ("bio","medium","How do vaccines train the immune system without causing disease?"),
 ("math","medium","What does the central limit theorem say and why is it useful?"),
 ("cs","medium","Why is UDP preferred for live video streaming?"),
 ("algo","extreme","How does a suffix automaton or suffix array enable fast substring queries?"),
 ("logic","medium","Why does correlation not imply causation, with an example?"),
 ("sysdesign","medium","What is the purpose of a message broker's dead-letter queue?"),
 ("physics","hard","Why does general relativity predict light bends around massive objects?"),
 ("chem","medium","Why are catalysts not consumed in a reaction?"),
 ("bio","hard","How does feedback inhibition regulate a metabolic pathway?"),
 ("math","hard","Why does the sum 1+2+...+n equal n(n+1)/2?"),
 ("cs","medium","Why can two's complement represent negative integers without a sign bit rule?"),
 ("algo","medium","Why is a hash collision unavoidable for large key spaces (pigeonhole)?"),
 ("logic","easy","If P implies Q and Q is false, what can you conclude about P?"),
 ("sysdesign","hard","How do you keep a cache consistent with the database it fronts?"),
 ("physics","medium","Why does a pendulum's period not depend on its mass?"),
 ("chem","easy","What is pH a measure of?"),
 ("bio","medium","Why is biodiversity important for ecosystem stability?"),
 ("math","medium","What is the difference between a permutation and a derangement?"),
 ("cs","hard","Why does a bloom filter have false positives but no false negatives?"),
 ("algo","hard","How does Dijkstra's algorithm guarantee correctness with a greedy choice?"),
 ("logic","hard","Why is proving 'there exists' easier than proving 'for all'?"),
 ("sysdesign","extreme","Design a deduplication layer for an at-least-once event pipeline."),
 ("physics","medium","Why does a wet cloth feel cool as it dries?"),
 ("chem","medium","Why does temperature affect the rate but not always the equilibrium constant?"),
 ("bio","easy","What is the difference between an artery and a vein?"),
 ("math","medium","Why is division by zero undefined but 0/5 is fine?"),
 ("cs","medium","Why does append-only logging simplify crash recovery?"),
 ("algo","medium","What is the difference between greedy and dynamic programming approaches?"),
 ("logic","medium","What is the difference between a tautology and a contradiction?"),
 ("sysdesign","medium","Why use a read-through cache instead of caching manually in code?"),
]


def main():
    path = "data/question_bank.json"
    bank = json.load(open(path, encoding="utf-8"))["tasks"]
    seen = {t["question"].strip().lower() for t in bank}
    nxt = max(int(t["id"].split("_")[1]) for t in bank if t["id"].split("_")[1].isdigit()) + 1
    added = 0
    for dom, diff, q in NEW:
        if q.strip().lower() in seen:
            continue
        seen.add(q.strip().lower())
        bank.append({"id": f"q_{nxt:03d}_{diff}_{dom}", "difficulty": diff, "question": q,
                     "max_steps": STEPS[diff], "expected": "graph-grounded explanation"})
        nxt += 1; added += 1
    os.makedirs("data", exist_ok=True)
    json.dump({"tasks": bank}, open(path, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
    print(f"added {added} new questions -> bank now {len(bank)} total")


if __name__ == "__main__":
    main()
